### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by alishahussain** [alishahussain/alishanew2025#6]
## **Integration Journey**
------
[Casino Integration Plan(**Team**)](https://github.com/orgs/CSA-Coders-2025/projects/3/views/11?pane=issue&itemId=88236367&issue=CSA-Coders-2025%7CPlanning-Repository-Issue-House-%7C38)
[Blackjack Integration Plan(**Individual**)](https://github.com/CSA-Coders-2025/Planning-Repository-Issue-House-/issues/62#issuecomment-2510538768)
[Key Commit Frontend](https://github.com/CSA-Coders-2025/CSA_Combined_Frontend_Fork/commit/bbeaea9bff160d4f768673aa1c137d918713aa4c)
[Key Commit Backend](https://github.com/CSA-Coders-2025/CSA_Combined_Backend_Fork/commit/5168a8004bc337b88c8d464d3129ebf3ae29af4f)

## **Tasks**
----
- [x] Adopt stocks' currency + scaling
- [x] Integrate fully with Gamify to put all casino games there
- [x] switch from user to person api
- [x] change user input from ID to email
- [x] add jwt token so data is saved
- [ ] Pull request on teacher repo and make sure everything works
- [ ] change styling to match up with game

## **Accomplishments**
----
- I added a slider instead of inputting balance on the game, and see the min and max so that it corresponds with the scaling of the stock game
- I added a JWT token that works with the user email, so when they play the game everything saves once they're logged in
- I changed my backend API code to work with JWT
- last trimester, I had my API mapped to the user API, so this trimester I edited my backend so that it works with Mort's person API. This helps many integration issues and makes it work with everyone else's code. 
- I was more collaborative this trimester, communicating with others in different periods, groups, and even withing my group. This is a really large integration project, so it's interesting to see how everyone is in communication with everyone else.
